In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../DMW_DataSets/Online Retail.csv',encoding='latin1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,88000,01-12-2010 08:26,700.00,17850.0,United Kingdom
1,536365,71053,REGENCY CAKESTAND 3 TIER,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [3]:
df_cleaned = df.dropna(subset=['Description', 'CustomerID']).copy()

In [4]:
price_bins = [-float('inf'), 0, 5, 20, 50, 100, 500, 1000, float('inf')]

price_labels = ['Invalid', 'Free', 'Cheap', 'Affordable', 'Moderate', 'Expensive', 'Very Expensive', 'Luxury']

In [5]:
df_cleaned.loc[:, 'PriceCategory'] = pd.cut(df_cleaned['UnitPrice'], bins=price_bins, labels=price_labels, include_lowest=True)
df_cleaned.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,PriceCategory
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,88000,01-12-2010 08:26,700.00,17850.0,United Kingdom,Very Expensive
1,536365,71053,REGENCY CAKESTAND 3 TIER,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,Free
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom,Free
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,Free
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,Free

In [6]:
qcut_quantity_labels = ['Very Low', 'Low', 'Medium', 'High']
df_cleaned.loc[:, 'QCutQualityCategory'] = pd.qcut(df_cleaned['Quantity'], q=4, labels=qcut_quantity_labels)
print(df_cleaned)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER     88000
1         536365     71053             REGENCY CAKESTAND 3 TIER         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

             InvoiceDate  UnitPrice  CustomerID         Country  \
0       01-12-2010 08:26     700.00     17850.0  United Kingdom
1       01-12-2010 08:26       3.39     17850.0  United Kingdom
2       01-12-2010 08:26       2.75     17850.0  United Kingdom
3       01-12-2010 08:26       3.39     17850.0  United Kingdom
4       01-12-2010 08:26       3.39     17850.0  United Kingdom
...                  ...        ...         ...             ...
541904  09-12-2011 12:50       0.85     12680.0          France
541905  09-12-2011 12:50       2.10     12680.0          France
541906  09-12-2011 12:50       4.15     12680.0          France
541907  09-12-2011 12:50       4.15     12680.0          France
541908  09-12-2011 12:50       4.95     12680.0          France

         PriceCategory QCutQualityCategory
0       Very Expensive                High
1                 Free              Medium
2                 Free              Medium
3                 Free              Medium
4                 Free              Medium
...                ...                 ...
541904            Free              Medium
541905            Free              Medium
541906            Free                 Low
541907            Free                 Low
541908            Free                 Low

[406829 rows x 10 columns]

In [7]:
product_hierarchy = {
    'WHITE HANGING HEART T-LIGHT HOLDER':'Home Decor',
    'REGENCY CAKESTAND 3 TIER':'Kitchenware',
    'RED RETROSPOT BIRD HOUSE':'Garden',
    'JUMBO BAG RED RETROSPOT':'Bag',
    'ASSORTED COLOUR BIRD ORNAMENT':'Home Decor'
}

In [8]:
df_cleaned.loc[:,'ProductCategory'] = df_cleaned['Description'].map(product_hierarchy).fillna('Other')

In [9]:
print('-----------------------------------')
print("\nUpdated Dataset with Discretization and Concept Hierarchy:")
print(df_cleaned.head())

-----------------------------------

Updated Dataset with Discretization and Concept Hierarchy:
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER     88000
1    536365     71053             REGENCY CAKESTAND 3 TIER         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

        InvoiceDate  UnitPrice  CustomerID         Country   PriceCategory  \
0  01-12-2010 08:26     700.00     17850.0  United Kingdom  Very Expensive
1  01-12-2010 08:26       3.39     17850.0  United Kingdom            Free
2  01-12-2010 08:26       2.75     17850.0  United Kingdom            Free
3  01-12-2010 08:26       3.39     17850.0  United Kingdom            Free
4  01-12-2010 08:26       3.39     17850.0  United Kingdom            Free

  QCutQualityCategory ProductCategory
0                High      Home Decor
1              Medium     Kitchenware
2              Medium           Other
3              Medium           Other
4              Medium           Other

In [ ]:
df_cleaned = df.dropna(subset=['Description', 'CustomerID']).copy()

price_bins = [-float('inf'), 0, 5, 20, 50, 100, 500, 1000, float('inf')]
price_labels = ['Invalid', 'Free', 'Cheap', 'Affordable', 'Moderate', 'Expensive', 'Very Expensive', 'Luxury']

df_cleaned.loc[:, 'PriceCategory'] = pd.cut(df_cleaned['UnitPrice'], bins=price_bins, labels=price_labels, include_lowest=True)
df_cleaned.head()

qcut_quantity_labels = ['Very Low', 'Low', 'Medium', 'High']
df_cleaned.loc[:, 'QCutQualityCategory'] = pd.qcut(df_cleaned['Quantity'], q=4, labels=qcut_quantity_labels)
print(df_cleaned)

product_hierarchy = {
    'WHITE HANGING HEART T-LIGHT HOLDER':'Home Decor',
    'REGENCY CAKESTAND 3 TIER':'Kitchenware',
    'RED RETROSPOT BIRD HOUSE':'Garden',
    'JUMBO BAG RED RETROSPOT':'Bag',
    'ASSORTED COLOUR BIRD ORNAMENT':'Home Decor'
}

df_cleaned.loc[:,'ProductCategory'] = df_cleaned['Description'].map(product_hierarchy).fillna('Other')

print('-----------------------------------')
print("\nUpdated Dataset with Discretization and Concept Hierarchy:")
print(df_cleaned.head())